Home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index,name='index'),
    path('about/', views.about,name='about'),
    path('contact/', views.contact,name='contact'),
    
    # path('basic/', views.basic,name='basic'),
    path('another/', views.another,name='another'),
    path('blogpage/', views.blogpage,name='blogpage'),
    path('chatbox/', views.chatbox,name='chatbox'),
    path('companyregistration/', views.companyregistration,name='companyregistration'),
    path('incometaxfilling/', views.incometaxfilling,name='incometaxfilling'),
    path('login/', views.Login,name='login'),
    path('memberlogin/', views.memberlogin,name='memberlogin'),
    path('membersignup/', views.membersignup,name='membersignup'),
    path('newsfeed/', views.newsfeed,name='newsfeed'),
    path('pvtltdreg/', views.pvtltdreg,name='pvtltdreg'),
    # path('privateltdreg/', views.privateltdreg,name='privateltdreg'),
    path('signup/', views.signup,name='signup'),
    path('signup1/', views.signup1,name='signup1'),
    path('signup2/', views.signup2,name='signup2'),
    # path('logindashboard', views.logindashboard, name="logindashboard"),
    path('payment/', views.payment, name="payment"),
    path('handlerequest/', views.handelrequest, name="handelrequest"),
    path('services/', views.services, name="services"),
    path('profile/', views.profile, name="profile"),
    path('editprofile/', views.editprofile, name="editprofile"),
    path('profile/changepass/', views.changepass, name="changepass"),
    path('profile/documents', views.document, name="documents"),
    path('profile/bookings', views.bookings, name="bookings"),
    path('getdoclist',views.getdoclist,name='getdoclist'),
    path('blog/<slug:slug>/', views.blog,name='blog'),
    path('blog/<slug:slug>/<slug:slug1>', views.blog,name='singleblog'),

]

cflax/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Home.urls')),
    path('',include('chat.urls')),
    path('tax/',include('othernavs.urls')),
    path('registration/',include('registration.urls')),
    path('taxfiling/',include('taxfiling.urls')),
    path('dashboard/',include('dashboard.urls'))
    
] +  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
 static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/urls.py
from django.urls import path,include
from . import views,otherNavViews
urlpatterns = [
    path('', views.index, name="dindex"),
    path('registrations/', views.registration, name="dregistration"),
    path('registrations/contact', views.contact, name="drcontact"),
    path('registrations/contact/delcontacts', views.delcontacts, name="delcontacts"),
    path('registrationsdelete/', views.deleteregistration, name="dsdeleteregistration"),
    path('registrations/<slug:slug>/', views.registration, name="dsregistration"),
    path('registrations/edit/<slug:slug1>/<slug:slug2>/', views.editregistration, name="dseditregistration"),
    # path('othernavs', otherNavViews.othernavs, name="dothernavs"),
    path('othernavsdelete/', otherNavViews.deleteothernavs, name="dsdeleteothernavs"),
    # path('othernavs/<slug:slug>', otherNavViews.othernavs, name="dsothernavs"),
    path('othernavs/contact', otherNavViews.contact, name="orcontact"),
    path('othernavs/contact/delcontacts', otherNavViews.delcontacts, name="odelcontacts"),
    path('othernavs/edit/<slug:slug1>/<slug:slug2>/', otherNavViews.editothernavs, name="dseditothernavs"),
    path('users/', views.alluser, name="alluser"),
    path('adminchat/', views.adminchat, name="adminchat"),
    path('adminchat/<slug:slug1>/<int:id>/', views.adminchat, name="adminchatuser"),
    path('adminchat/<slug:slug1>/<int:id>/clearchat/', views.clearchat, name="clearchat"),
    path('adminchat/<slug:slug1>/<int:id>/setpayment/', views.setpayment, name="setpayment"),
    path('getmsg/<slug:slug1>/<int:id>/', views.getmsg, name="admingetmsg"),

    path('dashboardlogout/', views.dashboardlogout, name="dashboardlogout"),
    path('edithome/', views.edithome, name="edithome"),
    path('edithome/<slug:slug>/', views.edithome, name="edithomeslug"),
    path('deletehome/<slug:slug>/', views.deletehome, name="deletehomeslug"),
    path('viewicon/', views.viewicon, name="viewiconslug"),
    path('', include('dashboard.superuserurls')),    
]

Home/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.db import models
from django.db.models.deletion import SET_NULL
from django.http import request
from dashboard.superuserviews import getEmailBackend
from registration.models import RegistrationSubMenu
from othernavs.models import RegistrationSubMenu as othernavsubmenu
from django.core.mail import  EmailMessage
from dashboard.models import makepaymentrequest
# Create your models here.
from datetime import datetime
class Slider(models.Model):
    objective = models.CharField(max_length=100)
    obj_details = models.TextField()
    img = models.ImageField(upload_to="img")
    def __str__(self) -> str:
        return self.objective
class aboutca(models.Model):
    title = models.CharField(max_length=50)
    content = RichTextField(blank=True,null=True)
    def __str__(self) -> str:
        return self.title
class ContactDetails(models.Model):
    email = models.EmailField()
    phone = models.CharField(max_length=13)
    address = models.TextField(max_length=100)
    otherPhones = models.CharField(max_length=100)
    def __str__(self) -> str:
        return self.email
from django.utils.html import strip_tags
class BusinessQuery(models.Model):
    name = models.CharField(max_length=30)
    phone = models.IntegerField()
    email = models.EmailField(max_length=50)
    message = models.CharField(max_length=500)
    reply = RichTextField(blank=True)
    def save(self):
        if len(self.reply)>7:
            backend,config = getEmailBackend()
            msg= strip_tags(self.reply)
            email = EmailMessage(
            "Kirnaaz: Query response",
            msg,
            config.email,
            [self.email],
            headers={'Reply-To': config.email},
            connection=backend
             )
            email.send()
        self.reply = ''
        super().save()
    def __str__(self) -> str:
        return self.name
class News(models.Model):
    date = models.DateField(auto_now_add=False,null=True,blank=True)
    news = models.TextField()
    def __str__(self) -> str:
        return self.date
class DueDateReminder(models.Model):
    date = models.DateField(auto_now_add=False,null=True,blank=True)
    details = models.TextField()
    def __str__(self) -> str:
        return self.date
class BlogNews(models.Model):
    Tchoice = (
        ('1','News'),
        ('2','Blogs'),
        ('3','Article'),
    )
    date = models.DateTimeField(auto_now=True)
    last_update = models.DateTimeField(auto_now=True)
    type = models.CharField(max_length=1, choices=Tchoice)
    img = models.ImageField(upload_to='blogs')
    title= models.CharField(max_length=200,null=True,blank=True)
    Short_des = models.CharField(max_length=500)
    content = RichTextField()
    def save(self, *args, **kwargs):
        self.last_update = datetime.now()
        super(BlogNews, self).save(*args, **kwargs)
    def Getchoices(self):
        return self.Tchoice
    def __str__(self) -> str:
        return self.title
class Offrings(models.Model):
    title = models.CharField(max_length=100)
    details = models.CharField(max_length=500)
    img = models.ImageField(upload_to="img")
    def __str__(self) -> str:
        return self.title
class headbanner(models.Model):
    banner_title = models.CharField(max_length=500,blank=True)
    banner_content = models.CharField(max_length=1500,blank=True)
    banneerimg = models.ImageField(upload_to="banner",blank=True)
    def __str__(self) -> str:
        return self.banner_title
class links(models.Model):
    title = models.CharField(max_length=50)
    page1 = models.ForeignKey(RegistrationSubMenu,on_delete=models.SET_NULL,blank=True,null=True)
    orpage2 = models.ForeignKey(othernavsubmenu,on_delete=models.SET_NULL,blank=True,null=True)
    def __str__(self) -> str:
        return self.title
class Expertise(models.Model):
    icon = models.ImageField(upload_to="imgaes")
    title = models.CharField(max_length=50)
    def __str__(self) -> str:
        return self.title
class marketplace(models.Model):
    icon = models.FileField(upload_to="imgaes")
    title = RichTextField(blank=True,null=True)
    def __str__(self) -> str:
        return self.title
class addblog(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="blogsimg")
    content = RichTextField(blank=True,null=True)
    time = models.DateTimeField(auto_now=True)
    def __str__(self) -> str:
        return self.title
class Payments(models.Model):
    order_id = models.CharField(unique=True, max_length=100, null=True, blank=True, verbose_name="Payments")
    payreq = models.ForeignKey(makepaymentrequest,on_delete=models.SET_NULL,null=True)
    status = models.CharField(max_length=50,default='pending')
    ammount = models.FloatField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order_date = models.DateTimeField(auto_now_add=True)
    other_data = models.CharField(max_length=1000,default="nodata")
    def save(self, *args, **kwargs):
        if self.order_id is None and self.order_date and self.id:
            self.order_id = self.order_date.strftime('PAY2ME%Y%m%dODR') + str(self.id)
        return super().save(*args, **kwargs)
    def __str__(self) -> str:
        return self.order_id
class documents(models.Model):
    user = models.ForeignKey(User,on_delete=SET_NULL,null=True)
    name = models.CharField(max_length=100)
    doc = models.FileField(upload_to="documents")
    time = models.DateTimeField(auto_now=True)
    def __str__(self) -> str:
        return self.name
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

class TaggedItem(models.Model):
    tag = models.SlugField()
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    def __str__(self):              # __unicode__ on Python 2
        return self.tag

dashboard/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import fields
from registration.models import RegistrationSubMenu
from othernavs.models import RegistrationSubMenu as othernavRegistrationSubMenu

# Create your models here.
class Sections(models.Model):
    reg_title = models.OneToOneField(RegistrationSubMenu,on_delete=models.CASCADE)
    section = models.CharField(max_length=1000,default='["Top Form section","Included in Our Packge","Procedure","Package icon","document","Memorandum","Register","FAQS","Signification","Our Clients"]')
    def __str__(self) -> str:
        return self.section
class Sectionsothernavs(models.Model):
    reg_title = models.OneToOneField(othernavRegistrationSubMenu,on_delete=models.CASCADE)
    section = models.CharField(max_length=1000,default='["Top Form section","Included in Our Packge","Procedure","Package icon","document","Memorandum","Register","FAQS","Signification","Our Clients"]')
    def __str__(self) -> str:
        return self.section
class makepaymentrequest(models.Model):
    user = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    reason = models.CharField(max_length=100)
    ammount = models.FloatField()
    status = models.CharField(max_length=20,default="pending")
    def __str__(self) -> str:
        return self.reason
class aboutContact(models.Model):
    logo = models.ImageField(upload_to="logo")
    AdminTitle = models.CharField(max_length=30)
    favicon  = models.ImageField(upload_to='logo')
    def __str__(self) -> str:
        return self.AdminTitle

class emailSetup(models.Model):
    host = models.CharField(max_length=100)
    port = models.IntegerField()
    email = models.CharField(max_length=100)
    tsl = models.BooleanField()
    ssl = models.BooleanField()
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    activate = models.BooleanField(help_text="other mail is automatically disabled")
    def save(self, *args, **kwargs):
        if self.activate:
            data=emailSetup.objects.all().exclude(id=self.id)
            data.update(activate=False)
        super(emailSetup, self).save(*args, **kwargs)
    def __str__(self) -> str:
        return self.email

dashboard/templates/alluser.html
{% extends 'dbasic.html' %}
        <!-- sidebar menu area start -->
{% block body %}   


{% endblock %}

dashboard/templates/dashboardhome.html
{% extends 'dbasic.html' %}
        <!-- sidebar menu area start -->
{% block body %}   

{% for form in forms %}
{% if forloop.counter > 1 and forloop.counter == forms|length %}
<div style="display:none" id="addnewslug">

{% endif %}
<div class="col-lg-12 my-3">
<div class="card">
<div class="card-body">
<h2 class="my-5">{{title}} {{forloop.counter}}</h2>
 <form action="{{request.get_full_path}}?{% if form.instance.id %}&object={{form.instance.id}}{% else %}&object=new{% endif %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary my-3" value="Submit">
        <button type="button" class="btn btn-danger  {% if form.instance.id %}{% else %}disabled{% endif %}" data-toggle="modal" data-target="#exampleModal{{form.instance.id}}">
            <i class="ti-trash"></i>Delete
          </button>
        
    </form>
    <div class="modal fade" id="exampleModal{{form.instance.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
        <form method="POST" action="{% url 'deletehomeslug' slug=slug %}">
            <div class="modal-body">
              <h3>Are You Sure.</h3>
            </div>
            {% csrf_token %}
            <input type="hidden" name="id" value="{{form.instance.id}}">
            <input type="hidden" name="page" value="{{request.GET.page}}">
            <input type="hidden" name="return" value="{{request.get_full_path}}">
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-danger">Yes Sure</button>
            </div>
        </form>
          </div>
        </div>
      </div>
</div>
</div>
</div>
{% if forloop.counter > 1 and forloop.counter == forms|length %}</div><button class="btn btn-primary mx-4" onclick="$('#addnewslug').toggle();">+Add {{slug}}</button>{% endif %}
{% endfor %}
{% endblock %}

dashboard/templates/dbasic.html
{% extends 'superuser2/basic.html' %}

dashboard/templates/editothernavs.html
{% extends 'dbasic.html' %}

{% block body %}
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css"
    integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.0-beta/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <style>
      .dropdown-menu label {
      margin: 10px;
      width: 30px;
      height: 30px;
  }
  
  .dropdown-menu {
      height:400px;
      overflow-y: scroll;
  }
      </style>
<div class="my-5"></div>
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}"><<</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1" aria-disabled="true"><<</a>
        </li>
      {% endif %}
      {% for i,j in sec %}
        {% if page_obj.number == i %}
          <li class="page-item active" aria-current="page">
            <span class="page-link">
              {{j}}
              <span class="sr-only">(current)</span>
            </span>
          </li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ j }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">>></a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1" aria-disabled="true">>></a>
        </li>
      {% endif %}
    </ul>
  </nav>
<div class="my-5"></div>
  
{% for form in page_obj %}
{% if form|length > 0 %}
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% if card_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{page_obj.number}}&card={{ card_obj.previous_page_number }}"><<</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true"><<</a>
      </li>
    {% endif %}
    {% for i in card_obj.paginator.page_range %}
      {% if card_obj.number == i %}
        <li class="page-item active" aria-current="page">
          <span class="page-link">
            {% for i,j in sec %}{% if page_obj.number == i %}{{j}}{% endif %}{% endfor %}{{i}}
            <span class="sr-only">(current)</span>
          </span>
        </li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{page_obj.number}}&card={{ i }}">{% if forloop.counter == card_obj.paginator.page_range|length %}Add New{% else %}{{ i }}{% endif %}</a></li>
      {% endif %}
    {% endfor %}
    {% if card_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{page_obj.number}}&card={{ card_obj.next_page_number }}">>></a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">>></a>
      </li>
    {% endif %}
  </ul>
</nav>
{% for f in card_obj %}
<div class="col-lg-12 my-2">
    <div class="card">
    <div class="card-body">
      <a class="btn btn-info btn-xs float-right my-4" target="_blank" href="{% url 'handlenav' slug1=slugs.0 slug2=slugs.1  %}" "="">
        <i class="ti-eye"> View Page</i>
    </a>
    <h1 class="my-4">{% for i,j in sec %}{% if page_obj.number == i %}{{j}}{% endif %}{% endfor %}{{i}} {{card_obj.number}}</h1>
    <form action="{{request.get_full_path}}{% if f.instance.id %}&object={{f.instance.id}}{% else %}&object=new{% endif %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
        {{ f.media }}
        {{ f.as_p }}
        {% if 'icon' in f.fields %}
        <div class="row my-4">
        <div class="container col-10 ">
            <li class="nav-item dropup" style="list-style-type: none;">
              <a class="nav-link dropdown-toggle btn btn-secondary" href="#" data-bs-toggle="dropdown">Choose Icon</a>
                <ul class="dropdown-menu col-md-10">
                  <div class="col-md-12">
                      {% for i in icon %}
                      <label class="fa {{i.icon}}" onmouseover="$('#showiconi').attr('class',this.className);
                      $('#id_icon').val(this.id)" id="{{forloop.counter}}"  onclick="$('#showiconi').attr('class',this.className);" for="icon{{forloop.counter}}"></label><input type="radio" style="display: none;" id="icon{{forloop.counter}}" name="icons">
                    {% endfor %}
                  </div>
                </ul>
            </li>
        </div>
        <div class="col"><h1><i class="fa {{f.instance.icon}}" id='showiconi'></i></h1></div>
        </div>
        {% endif %}
        <input type="submit" class="btn btn-primary my-3" value="Submit">
        <button type="button" class="btn btn-danger  {% if f.instance.id %}{% else %}disabled{% endif %}" data-toggle="modal" data-target="#exampleModal{{f.instance.id}}">
            <i class="ti-trash"></i>Delete
          </button>
        
    </form>
    
      
      <!-- Modal -->
      <div class="modal fade" id="exampleModal{{f.instance.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
        <form method="POST" action="{% url 'dsdeleteothernavs' %}">
            <div class="modal-body">
              <h3>Are You Sure.</h3>
            </div>
            {% csrf_token %}
            <input type="hidden" name="id" value="{{f.instance.id}}">
            <input type="hidden" name="page" value="{{request.GET.page}}">
            <input type="hidden" name="return" value="{{request.get_full_path}}">
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-danger">Yes Sure</button>
            </div>
        </form>
          </div>
        </div>
      </div>
    
        </div>
    </div>
    </div>
    {% endfor %}
{% else %}
<div class="col-lg-12 my-2">
<div class="card">
<div class="card-body">
<a class="btn btn-info btn-xs float-right my-4" target="_blank" href="{% url 'handlenav' slug1=slugs.0 slug2=slugs.1  %}" "="">
        <i class="ti-eye"> View Page</i>
    </a>
<h1 class="my-4">{% for i,j in sec %}
  {% if page_obj.number == i %}{{j}}{% endif %}{% endfor %}</h1>
<form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary my-3" value="Submit">
    <button type="button" class="btn btn-danger {% if form.instance.id %}{% else %}disabled{% endif %}" data-toggle="modal" data-target="#exampleModal{{f.instance.id}}">
        <i class="ti-trash"></i>Delete
      </button>
</form>
</div>
</div>
</div>
<div class="modal fade" id="exampleModal{{f.instance.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
    <form method="POST" action="{% url 'dsdeleteothernavs' %}">
        <div class="modal-body">
          <h3>Are You Sure.</h3>
        </div>
        {% csrf_token %}
        <input type="hidden" name="id" value="{{form.instance.id}}">
        <input type="hidden" name="page" value="{{request.GET.page}}">
        <input type="hidden" name="return" value="{{request.get_full_path}}">
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-danger">Yes Sure</button>
        </div>
    </form>
      </div>
    </div>
  </div>

    </div>
</div>
</div>
{% endif %}

{% endfor %}


<!-- Button trigger modal -->

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

{% endblock %}